apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
  labels:
    app: simple-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      imagePullSecrets:
        - name: ecr-secret  # <<----- This is the important line
      containers:
        - name: simple-webapp
          image: 881490102094.dkr.ecr.ap-southeast-1.amazonaws.com/simple-webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
